add book 1 translation into Ukrainian
getify/You-Dont-Know-JS pull request #1720
Opened 2021-01-06 10:30 UTC by AMashoshyna

This PR adds book 1 translation into Ukrainian by @croftyland and myself. Book 2 is in progress.

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

Specifically quoting these guidelines regarding typos:

> Typos?
>
> Please don't worry about minor text typos. These will almost certainly be caught during the editing process.
>
> If you're going to submit a PR for typo fixes, please be measured in doing so by collecting several small changes into a single PR (in separate commits). Or, **just don't even worry about them for now,** because we'll get to them later. I promise.

----

**Please type "I already searched for this issue":**
I already searched for this issue

**Edition:** (pull requests not accepted for previous editions)

**Book Title:**

**Chapter:**

**Section Title:**

**Topic:**

2021-01-06 14:02 UTC, getify requested changes
LGTM.

Could we also translate the main root README so that when Ukranian readers land on this repository, they see all the welcome text in the expected language?

2021-01-06 14:04 UTC, AMashoshyna commented
Sure! Working on it.

2021-01-07 16:20 UTC, getify approved these changes

2021-01-07 16:23 UTC, merged

2021-01-07 16:23 UTC, getify commented
Great, thanks so much for your work!