fixed typo
getify/You-Dont-Know-JS pull request #483
Opened 2015-07-06 21:10 UTC by matchabros

Just a quick typo fix.

2015-07-09 14:17 UTC, getify commented
That change makes the sentence into a fragment, since it removes the verb "is".

2015-07-09 14:24 UTC, matchabros commented
But it sounds so weird! Anyway, apologies for the unnecessary commit.

2015-07-09 14:26 UTC, getify commented
Could perhaps have had a comma or colon in between "is" and "the", such as:

> Another thing `configurable:false` prevents is, the ability to use the `delete` operator to remove an existing property.

> Another thing `configurable:false` prevents is: the ability to use the `delete` operator to remove an existing property.

Do either of those changes make it read clearer to you?

2015-07-09 14:30 UTC, bmacdonald-oreilly commented
From a grammatical standpoint, there shouldn't be any punctuation there. However, when the "sounds wrong" objection comes up, the solution is usually "recast the sentence," like so:

configurable:false also prevents you from using the delete operator to remove an existing property.

Or if you don't like starting the sentence with a lower-case code term:

Also, configurable:false prevents you from using the delete operator to remove an existing property.

2015-07-09 14:43 UTC, matchabros commented
Changes proposed by bmacdonald-oreilly are fine. 

Don't get me wrong, everything is clear in that sentence, but feels weird while reading it - knocks you out of the flow to be more precise.

2020-03-11 12:33 UTC, shivaylamba requested changes
Please fix merge conflicts.

2025-09-03 19:12 UTC, closed without merging